# Generated by Django 3.0.5 on 2020-04-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['issuedate']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['modelnum']},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuedate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
