# Generated by Django 3.0.5 on 2020-04-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200417_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='fifequency',
            new_name='fifrequency',
        ),
    ]
