# Generated by Django 3.0.5 on 2020-04-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200417_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modelnum',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
