# Generated by Django 3.0.5 on 2020-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('first', models.TextField()),
                ('middle', models.TextField()),
                ('last', models.TextField()),
                ('job', models.TextField()),
                ('email', models.TextField()),
                ('office', models.TextField()),
                ('cell', models.TextField()),
                ('prefix', models.TextField()),
                ('staff', models.TextField()),
            ],
        ),
    ]
