# Generated by Django 3.0.5 on 2020-05-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientCode', models.CharField(max_length=60)),
                ('clientName', models.CharField(max_length=60)),
                ('clientType', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('modelnum', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('celltechnology', models.CharField(max_length=60)),
                ('manufacturer', models.CharField(max_length=60)),
                ('cellsinseries', models.IntegerField()),
                ('seriesstrings', models.IntegerField()),
                ('bypassdiodes', models.IntegerField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('weight', models.FloatField()),
                ('supertype', models.CharField(max_length=60)),
                ('supermanufacturer', models.CharField(max_length=60)),
                ('subtype', models.CharField(max_length=60)),
                ('submanufacturer', models.CharField(max_length=60)),
                ('frametype', models.CharField(max_length=60)),
                ('frameadhesive', models.CharField(max_length=60)),
                ('encaptype', models.CharField(max_length=60)),
                ('encapmanufacturer', models.CharField(max_length=60)),
                ('junctype', models.CharField(max_length=60)),
                ('juncmanufacturer', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['modelnum'],
            },
        ),
        migrations.CreateModel(
            name='TestSequence',
            fields=[
                ('sequenceid', models.AutoField(primary_key=True, serialize=False)),
                ('sequencename', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['sequencename'],
            },
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('standardid', models.AutoField(primary_key=True, serialize=False)),
                ('standardname', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('publishdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('first', models.CharField(max_length=60)),
                ('middle', models.CharField(max_length=60)),
                ('last', models.CharField(max_length=60)),
                ('job', models.CharField(max_length=60)),
                ('email', models.EmailField(help_text='sample@gmail.com', max_length=254)),
                ('office', models.CharField(help_text='Enter as XXX-XXX-XXXX', max_length=60)),
                ('cell', models.CharField(help_text='Enter as XXX-XXX-XXXX', max_length=60)),
                ('prefix', models.CharField(max_length=60)),
                ('staff', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=3)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpvsite.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceid', models.AutoField(primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('firequired', models.BooleanField()),
                ('fifrequency', models.CharField(max_length=60)),
                ('standardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpvsite.TestStandard')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxvolt', models.IntegerField()),
                ('voc', models.FloatField()),
                ('isc', models.FloatField()),
                ('vmp', models.FloatField()),
                ('imp', models.FloatField()),
                ('pmp', models.FloatField()),
                ('ff', models.FloatField()),
                ('modelnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpvsite.Product')),
                ('sequenceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpvsite.TestSequence')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=60)),
                ('address2', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('postalcode', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=60)),
                ('phonenumber', models.CharField(max_length=11)),
                ('faxnumber', models.CharField(max_length=11)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpvsite.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certid', models.AutoField(primary_key=True, serialize=False)),
                ('reportnum', models.IntegerField()),
                ('issuedate', models.DateField(auto_now_add=True)),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpvsite.Location')),
                ('modelnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpvsite.Product')),
                ('standardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpvsite.TestStandard')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpvsite.User')),
            ],
            options={
                'ordering': ['issuedate'],
            },
        ),
    ]
