# Generated by Django 3.0.5 on 2020-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpvsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['clientName']},
        ),
        migrations.AlterField(
            model_name='client',
            name='clientCode',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cell',
            field=models.CharField(help_text='Enter as XXX-XXX-XXXX', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='sample@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.CharField(help_text='Enter as XXX-XXX-XXXX', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefix',
            field=models.CharField(choices=[('DR', 'Dr'), ('MR', 'Mr'), ('MS', 'Ms'), ('MRS', 'Mrs')], default='DR', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
