# Generated by Django 3.0.5 on 2020-05-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpvsite', '0002_auto_20200501_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientCode',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
