# Generated by Django 3.0.5 on 2020-05-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpvsite', '0005_auto_20200501_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientCode',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='faxnumber',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='phonenumber',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
